config/routes.rb
Rails.application.routes.draw do

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "publics/registrations",
    sessions: "publics/sessions"
  }

  devise_for :admins

  namespace :publics do
    get 'homes/top'

    resources :items, only: [:index, :show]
     get '/customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    resources :customers, only: [:index, :show, :edit, :update]
    patch '/customers/:id/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
    resources :genres, only: [:show]
    resources :cart_items, only: [:index, :update, :destroy, :create]do
       collection do
         delete "destroy_all"   #パスが　all_destroy_cart_items_path, method: :delete　となる
       end
     end
    patch '/customers/:id' => 'customers#update', as: 'update_cart_item'
    post '/orders/confirm'
    get '/orders/complete'
    resources :orders, only: [:new, :create, :index, :show]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  namespace :admins do
    get 'homes/top'

    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
    resources :customers, only: [:index, :show, :edit, :update]
    patch 'customers/:id' => 'customers#update', as: 'update_customer'
    resources :genres, only: [:index, :create, :edit, :update]
    # get 'genres/index'
    # post 'genres' => 'genres#create'
    # get 'genres/edit'
    # patch 'genres/:id' => 'genres#update', as: 'update_genre'
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    # get 'items/index'
    # get 'items/new'
    # post 'items' => 'items#create'
    # get 'items/show'
    # get 'items/edit'
    patch 'items/:id' => 'items#update', as: 'update_item'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'homes#top'
  get '/' => 'homes#top'
  get '/homes/about'


  # , controllers: {
  #  registrations: "admins/registrations",
  #  sessions: "admins/sessions",
  #  passwords: "admins/passwords",
  #  confirmations: "admins/confirmations"
  # }


  # , controllers: {
  #  registrations: "users/registrations",
  #  sessions: "users/sessions",
  #  passwords: "users/passwords",
  #  confirmations: "users/confirmations"
  # }

end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :item
  belongs_to :customer

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses

  has_many :cart_items

  has_many :orders


  def active_for_authentication?
    super && (is_deleted == false)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  # has_many :item_genre_relations
  # has_many :items, through: :item_genre_relations
  has_many :items

  validates :genres_name, presence:true

end

app/models/item.rb
class Item < ApplicationRecord

  # has_many :item_genre_relations
  # has_many :genres, through: :item_genre_relations
  belongs_to :genre

  has_many :cart_items
  validates :price, presence: true

  has_many :order_details


  has_one_attached :image

  def add_tax_price
    (self.price * 1.10).round
  end

  validates :is_active, inclusion: { in: [true, false] }

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end



end

app/models/item_genre.rb
class ItemGenre < ApplicationRecord
  # belongs_to :item
  # belongs_to :genre
end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer

  has_many :order_details

  enum payment_method:{クレジットカード: 0, 銀行振込: 1}
  enum status:{入金待ち: 0, 入金確認: 1, 製作中: 2,発送準備中: 3, 発送済み: 4}

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order

  belongs_to :item

  enum making_status:{製作不可: 0, 製作待ち: 1, 製作中: 2, 製作完了: 3}

end

app/models/public.rb
class Public < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admins_item_path(@item.id)
  end

  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
       flash[:notice] = "You have created book successfully."
       redirect_to admins_item_path(@item.id)
    else
      render 'edit'
    end
  end

private

  def item_params
    params.require(:item).permit(:item_name, :image, :item_introduction, :genre_id, :price, :is_active)
  end

end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def new
  end

  def index
  end

  def show
  end

  def edit
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  # def after_sign_up_path_for(resource)
  #   case resource
  #   when Admin
  #       admins_homes_top_path
  #   when Customer
  #       publics_customer_path(resource)
  #   end
  # end

  def after_sign_in_path_for(resource)
     case resource
     when Admin
        admins_homes_top_path
     when Customer
        root_path
     end
  end

  def after_sign_out_path_for(resource_or_scope)
      if resource_or_scope == :admin
        new_admin_session_path
      else
        root_path
      end
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name_kana])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name_kana])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:postal_code])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:address])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:telephone_number])
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @items = Item.all.limit(4)
    @genres = Genre.all
  end
end

app/controllers/publics/items_controller.rb
class Publics::ItemsController < ApplicationController
  def index
    @items = Item.page(params[:page]).per(8)
    @genres = Genre.all
  end

  def show
    @item = Item.find(params[:id])
    @cart_item =CartItem
    @genres = Genre.all
  end
end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/helpers/admins/homes_helper.rb
module Admins::HomesHelper
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/publics/genres_helper.rb
module Publics::GenresHelper
end

app/helpers/publics/homes_helper.rb
module Publics::HomesHelper
end

app/helpers/publics/items_helper.rb
module Publics::ItemsHelper
end

app/helpers/publics/orders_helper.rb
module Publics::OrdersHelper
end

app/views/admins/items/edit.html.erb
<main>
<div class="container">

  <h3>商品編集</h3>

  <div class="item_edit">
    <%= form_with model: @item, url: admins_update_item_path(@item.id), method: :patch do |f| %>
  <table class="order-table table mb-5">
    <tbody>
      <tr>
        <th>商品画像</th>
        <td><%= f.file_field :image, accept: "image/*" %></td>
      </tr>
      <tr>
        <th>商品名</th>
        <td><%= f.text_field :item_name, :size=>"40" %></td>
      </tr>
      <tr>
        <th>商品説明</th>
        <td><%= f.text_area :item_introduction, :size=>"43x7" %></td>
      </tr>
      <tr>
        <th>ジャンル</th>
        <td><%= f.collection_select :genre_id, Genre.all, :id, :genres_name %></td>
      </tr>
      <tr>
        <th>税抜価格</th>
        <td><%= f.text_field :price, :size=>"40" %> 円</td>
      </tr>
      <tr>
        <th>販売ステータス</th>
        <td>
          <%= f.radio_button :is_active, "true" %>販売中
          <%= f.radio_button :is_active, "false" %>販売停止中
        </td>
      </tr>
    </tbody>
  </table>

    <div class="text-center">
      <%= f.submit '変更を保存', class:"btn btn-success" %>
    </div>
    
  <% end %>
</div>

  </div>

</main>

app/views/admins/items/index.html.erb
<main>
<div class="container">
  <div class="row">

    <div class="container mt-4 pb-3">
      <div class="display-2">
        <h3>商品一覧</h3>
      </div>
      <div class="text-right">
        <%= link_to "＋", new_admins_item_path, class:"btn btn-outline-secondary rounded-circle p-0", style:"width:2rem;height:2rem;" %>
      </div>
    </div>

  <table class="order-table table mb-5">
      <thead>
        <tr>
          <th>商品ID</th>
          <th>商品名</th>
          <th>税抜価格</th>
          <th>ジャンル</th>
          <th>ステータス</th>
        </tr>
      </thead>

      <% @items.each do |item| %>
      <tbody>
        <tr>
          <td style="width: 10%"><%= item.id %></td>
          <td style="width: 30%"><%= link_to item.item_name, admins_item_path(item.id) %></td>
          <td><%= item.price %></td>
          <td><%= item.genre.genres_name %></td>
          <td>
            <% if item.is_active %>
                <div class="text-success">販売中</div>
            <% elsif %>
                販売停止中
            <% end %>
          </td>
        </tr>
      </tbody>
<% end %>
</table>
<%= paginate @items %>

  </div>
</div>
</main>

app/views/admins/items/new.html.erb
<main>
<div class="container">

  <h3>商品新規登録</h3>

  <div class="item_edit">
    <%= form_with model: @item, url: admins_items_path do |f| %>
    <table class="order-table table mb-5">
      <tbody>
        <tr>
          <th>商品画像</th>
          <td><%= f.file_field :image, accept: "image/*" %></td>
        </tr>
        <tr>
          <th>商品名</th>
          <td><%= f.text_field :item_name, :size=>"40" %></td>
        </tr>
        <tr>
          <th>商品説明</th>
          <td><%= f.text_area :item_introduction, :size=>"43x7" %></td>
        </tr>
        <tr>
          <th>ジャンル</th>
          <td><%= f.collection_select :genre_id, Genre.all, :id, :genres_name %></td>
        </tr>
        <tr>
          <th>税抜価格</th>
          <td><%= f.text_field :price, :size=>"40" %> 円</td>
        </tr>
        <tr>
          <th>販売ステータス</th>
          <td>
            <%= f.radio_button :is_active, "true" %>販売中
            <%= f.radio_button :is_active, "false" %>販売停止中
          </td>
        </tr>
      </tbody>
    </table>

    <div class="text-center">
      <%= f.submit '新規登録', class:"btn btn-success" %>
    </div>

    <% end %>
  </div>

</div>
</main>

app/views/admins/items/show.html.erb
<main>
<div class="container">
  <div class="row">

    <div class="display-2  mt-4 pb-3">
      <h3>商品詳細</h3>
    </div>

    <div class="container">
      <div class="items-show_list">
          <%= image_tag @item.get_image, :size =>"250x230" %>

        <table class="items-show_list_text">
          <tbody>
            <tr>
              <th>商品名</th>
              <td><%= @item.item_name %></td>
            </tr>
            <tr>
              <th>商品説明</th>
              <td><%= @item.item_introduction %></td>
            </tr>
            <tr>
              <th>ジャンル</th>
              <td><%= @item.genre.genres_name %></td>
            </tr>
            <tr>
              <th>税込価格(税抜価格)</th>
              <td><%= @item.price.to_s(:delimited) %>(<%= @item.add_tax_price.to_s(:dalimited) %>) 円</td>
            </tr>
            <tr>
              <th>販売ステータス</th>
              <td>
                <% if @item.is_active %>
                    販売中
                <% elsif %>
                    販売停止中
                <% end %>
              </td>
            </tr>

          </tbody>
        </table>
      </div>

      <div class="text-center">
        <%= link_to "編集する", edit_admins_item_path(@item.id), class:"btn btn-success" %>
      </div>
    </div>

  </div>
</div>
</main>